### ISSUE TITLE
Avoid platfrom-specific commands, use Python

### ISSUE THREAD

**Issue by wenzeslaus** [chaedri/GIS714-assignments#6]
Avoid the need to include commands for Windows and Unix such as

```
# Linux/Mac
# !rm ../grassdata/baranjahill.zip
# !rm -rf ../grassdata/tmp/

# Windows
!del ..\grassdata\baranjahill.zip
!rd /s /q  ..\grassdata\tmp
```

Instead, use Python functions when a command is not available, [shutil](https://docs.python.org/3/library/shutil.html) can do just that.

This will allow you to construct the path more easily, e.g., with the [Path](https://docs.python.org/3/library/pathlib.html) object, e.g., `Path("grassdata") / "tmp"` if needed (since Python 3.7 _Path_ works in combination with _shutil_).

For the record, I think `!rm ...` in notebooks is a neat thing in general, but if we want cross-platform notebooks which are convenient to use, then pure-Python works better.

**Comment by chaedri** [comment]
I switched all the command line calls in Assignment 3C to python except for the `curl` command since I think it works on all operating systems and I couldn't find a straight-forward python method.
