### ISSUE TITLE
Adding files under grassdata may be confusing

### ISSUE THREAD

**Issue by wenzeslaus** [chaedri/GIS714-assignments#7]
This is a common issue, do you put your baranjahill.zip or elevations.shp under grassdata or somewhere else? I think grassdata is specifically meant for data managed by GRASS GIS, so you should not manipulate the data there yourself in general, hence data to be imported or exported should not be there.

This creates a need for another directory besides grassdata, e.g., data. Then the question arises if grassdata directory should be under or next to data. Both works for me.

However, especially for simple or project-oriented cases, another approach may make sense. GRASS locations can be directly under data because there is no requirement that the directory with GRASS locations contains only GRASS locations. Hence renaming the original grassdata to data is a valid step in my opinion.

**Comment by chaedri** [comment]
I'm leaning towards your last suggestion since having a data folder for the assignments in the repository seems like a neat/tidy way to manage both file paths (see Issue #10) and this one.
