### ISSUE TITLE
All R code should have R cell magic instead of switching R kernel

### ISSUE THREAD

**Issue by wenzeslaus** [chaedri/GIS714-assignments#8]
If R is used in a cell, the cell should have `%%R` instead of asking people to switch back and forth between kernels. Ideally, notebooks should be executable automatically without user intervention, so manually switching a kernel in the middle of the notebook is not a good option.

**Comment by chaedri** [comment]
I think this is fixed in my latest commit/push. I figured out how to get %%R working. No more switching kernels!
